name: Vue Test

on:
  push:
    branches: [ '*' ]

jobs:
  test:
    name: vue test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.16.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
